version: '3.4'

services:
    php:
        image: zigift-php
        build: ./docker/php
        container_name: zigift_php
        volumes:
            - ./project:/var/www
            - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        depends_on:
            - mysql
        environment:
            - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@zigift_mysql:3306/${MYSQL_DATABASE}
            - APP_ENV
            - APP_SECRET
            - WECHAT_APP_ID
            - WEHACHT_APP_SECRET

    nginx:
        image: zigift-nginx
        build: ./docker/nginx/
        container_name: zigift_nginx
        volumes:
            - ./docker/nginx/zigift.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "88:80"
        volumes_from:
            - php
        links:
            - php

    mysql:
        image: percona:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_DATABASE=zigift
            - MYSQL_USER=sylius
            - MYSQL_PASSWORD=123456
        volumes:
             - ./docker/mysql/data:/var/lib/mysql:rw,delegated
        ports:
            - "3307:3306"
