version: '3.4'

services:
    php:
        image: zigift-php
        build: ./docker/php
        container_name: zigift_php
        volumes:
            - ./project:/var/www
            - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        links:
           - mysql
        depends_on:
            - mysql
        environment:
            - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_CONTAINER_ADDRESS}:${MYSQL_CONTAINER_PORT}/${MYSQL_DATABASE}
            - APP_ENV
            - APP_SECRET
            - WECHAT_APP_ID
            - WEHACHT_APP_SECRET

    nginx:
        image: zigift-nginx
        build: ./docker/nginx/
        container_name: zigift_nginx
        volumes:
            - ./docker/nginx/zigift.conf:/etc/nginx/conf.d/default.conf
            - ./project:/var/www
        ports:
            - "${NGINX_CONTAINER_PORT}:80"
#        volumes_from:
#            - php
        links:
            - php

    mysql:
        image: percona:5.7
        environment:
            - MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
        volumes:
             - ./docker/mysql/data:/var/lib/mysql:rw,delegated
        ports:
            - "${MYSQL_CONTAINER_PORT}:3306"
