admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    defaults:
        _locale: '%locale%'
    prefix: /admin
    options:
        i18n: false

_sonata_admin:
    resource: .
    type: sonata_admin
    defaults:
        _locale: '%locale%'
    prefix: /admin
    options:
        i18n: false

app_admin_ajax:
    resource: "admin/ajax.yaml"
    prefix: /admin/ajax
    defaults:
        _locale: '%locale%'
    options:
        i18n: false
