knp_gaufrette:
    adapters:
        image_adapter:
            local:
                directory:  '%kernel.project_dir%/public/uploads/img'
                create:     true
        root_adapter:
            local:
                directory: '%kernel.project_dir%/public'

    stream_wrapper: ~

    filesystems:
        image_fs:
            adapter: image_adapter
            alias:   image_fs
        root_fs:
            adapter: root_adapter
            alias:   root_fs
