sylius_resource:
    resources:
        app.customer:
            classes:
                model: App\Entity\Client\Customer
                interface: App\Component\Model\CustomerInterface
                repository: App\Repository\Client\CustomerRepository
                form: App\Form\Type\Customer\CustomerType
        app.category:
            classes:
                model: App\Entity\Shop\Category
                interface: App\Component\Model\CategoryInterface
                repository: App\Repository\Shop\CategoryRepository
        app.category_image:
            classes:
                model: App\Entity\Shop\CategoryImage
                interface: App\Component\Model\ImageInterface
                form: App\Form\Type\Shop\CategoryImageType
        app.product:
            classes:
                model: App\Entity\Shop\Product
                interface: App\Component\Model\ProductInterface
                repository: App\Repository\Shop\ProductRepository
        app.product_image:
            classes:
                model: App\Entity\Shop\ProductImage
                interface: App\Component\Model\ImageInterface
                form: App\Form\Type\Shop\ProductImageType
        app.partner:
            classes:
                model: App\Entity\Partner\Partner
        app.partner_image:
            classes:
                model: App\Entity\Partner\PartnerImage
                form: App\Form\Type\Partner\PartnerImageType
        app.order:
            classes:
                model: App\Entity\Order\Order
                interface: App\Component\Model\OrderInterface
                repository: App\Repository\Order\OrderRepository
                controller: App\Controller\Shop\OrderController
        app.order_item:
            classes:
                model: App\Entity\Order\OrderItem
                interface: App\Component\Model\OrderItemInterface
                repository: App\Repository\Order\OrderItemRepository
                controller: App\Controller\Shop\OrderItemController
                form: App\Form\Type\Order\OrderItemType
