sylius_user:
    driver: doctrine/orm
    resources:
        admin:
            user:
                classes:
                    model: 'App\Entity\Admin\AdminUser'
                    repository: App\Repository\Admin\AdminUserRepository
                    form: App\Form\Type\User\AdminUserType
                    interface: App\Component\Model\AdminUserInterface
                    controller: Sylius\Bundle\UserBundle\Controller\UserController
                    factory: Sylius\Component\Resource\Factory\Factory
                templates: 'SyliusUserBundle:User'
                resetting:
                    token:
                        ttl: P1D
                        length: 16
                        field_name: passwordResetToken
                    pin:
                        length: 4
                        field_name: passwordResetToken
                verification:
                    token:
                        length: 16
                        field_name: emailVerificationToken
        shop:
            user:
                classes:
                    model: App\Entity\Client\ShopUser
                    repository: App\Repository\Client\UserRepository
                    form: App\Form\Type\User\ShopUserType
                    interface: App\Component\Model\ShopUserInterface
                    controller: Sylius\Bundle\UserBundle\Controller\UserController
                    factory: Sylius\Component\Resource\Factory\Factory
                templates: 'SyliusUserBundle:User'
                resetting:
                    token:
                        ttl: P1D
                        length: 16
                        field_name: passwordResetToken
                    pin:
                        length: 4
                        field_name: passwordResetToken
                verification:
                    token:
                        length: 16
                        field_name: emailVerificationToken
        oauth:
            user:
                classes:
                    model: Sylius\Component\User\Model\UserOAuth
                    interface: Sylius\Component\User\Model\UserOAuthInterface
                    controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
                    factory: Sylius\Component\Resource\Factory\Factory
                    form: Sylius\Bundle\UserBundle\Form\Type\UserType
                templates: 'SyliusUserBundle:User'
                resetting:
                    token:
                        ttl: P1D
                        length: 16
                        field_name: passwordResetToken
                    pin:
                        length: 4
                        field_name: passwordResetToken
                verification:
                    token:
                        length: 16
                        field_name: emailVerificationToken
