vich_uploader:
    db_driver: orm
    storage: gaufrette
    mappings:
        product_image:
            uri_prefix: /uploads/img
            upload_destination: image_fs
            delete_on_remove: true
            delete_on_update: true
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            directory_namer: vich_uploader.directory_namer_subdir

        category_image:
            uri_prefix: /uploads/img
            upload_destination: image_fs
            delete_on_remove: true
            delete_on_update: true
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            directory_namer: vich_uploader.directory_namer_subdir

        partner_image:
            uri_prefix: /uploads/img
            upload_destination: image_fs
            delete_on_remove: true
            delete_on_update: true
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            directory_namer: vich_uploader.directory_namer_subdir
