App\Entity\Client\Customer:
    constraint:
        Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            message: 
            fields: emailCanonical
            errorPath: email
    properties:
        firstName:
            - NotBlank:
                message: sylius.customer.first_name.not_blank
                groups: customer_profile
            - Length:
                min: 2
                minMessage: sylius.customer.first_name.min
                max: 255
                maxMessage: sylius.customer.first_name.max
        lastName:
            - NotBlank:
                message: sylius.customer.last_name.not_blank
                groups: customer_profile
            - Length:
                min: 2
                minMessage: sylius.customer.last_name.min
                max: 255
                maxMessage: sylius.customer.last_name.max
        email:
            - NotBlank:
                message: sylius.customer.email.not_blank
                groups: [customer_guest]
            - Length: 
                max: 254
                maxMessage: sylius.customer.email.max
                groups: [customer_guest]
            - Email: 
                message: sylius.customer.email.invalid
                groups: [customer_guest]
    
App\Entity\Shop\Category:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: url
    properties:
        parent:
            - Expression:
                expression: 'this.getId() == null or this.getId() != value.getId()'
        translations:
            - Count:
                  min: 1
                  minMessage: 'You must specify at least {{ limit }} Translation'
        slug:
            - Regex:
                  pattern: '/^[\d\w\-\_]+$/iu'

App\Entity\Shop\CategoryTranslation:
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 2
                max: 64
                maxMessage: 'Your name cannot be longer than {{ limit }} characters'

App\Entity\Shop\Product:
    constraints:
        -   Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: url
    properties:
        category:
            - NotBlank: ~
        translations:
            -   Count:
                    min: 1
                    minMessage: 'You must specify at least {{ limit }} Translation'
        code:
            -   NotBlank: ~
            -   Length:
                    min: 2
                    max: 64
        slug:
            - Regex:
                  pattern: '/^[\d\w\-\_]+$/iu'

App\Entity\Shop\ProductTranslation:
    properties:
        name:
            - NotBlank: ~
            - Length:
                  min: 2
                  max: 128
                  maxMessage: 'Your name cannot be longer than {{ limit }} characters'
