services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../../src/*'
        exclude: '../../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../../src/Controller'
        tags: ['controller.service_arguments']

    App\Form\EventSubscriber\:
        resource: '../../src/Form/EventSubscriber'
        autowire: false
        autoconfigure: false

    Sylius\Component\User\Canonicalizer\CanonicalizerInterface:
        alias: sylius.canonicalizer

    Sylius\Component\User\Security\PasswordUpdaterInterface:
        alias: sylius.security.password_updater

    App\Routing\CatalogLoader:
        arguments:
            - '@app.repository.category'
            - '@app.repository.product'
        tags:
            - { name: 'routing.loader' }
