imports:
    - { resource: 'parameters.yaml' }
    - { resource: 'services/defaults.yaml' }
    - { resource: 'services/event_listener.yaml' }
    - { resource: 'services/form.yaml' }
    - { resource: 'services/admin.yaml' }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    app.admin_user_provider.email_based:
        class: Sylius\Bundle\UserBundle\Provider\EmailProvider
        arguments:
            - '%sylius.model.admin_user.class%'
            - '%sylius.repository.admin_user.class%'
            - '@sylius.canonicalizer'

    app.shop_user_provider.email_based:
        class: Sylius\Bundle\UserBundle\Provider\EmailProvider
        arguments:
            - '%sylius.model.shop_user.class%'
            - '@sylius.repository.shop_user'
            - '@sylius.canonicalizer'

    App\OAuth\UserProvider:
        arguments:
            - "%sylius.model.shop_user.class%"
            - "@app.factory.customer"
            - "@sylius.factory.shop_user"
            - "@sylius.repository.shop_user"
            - "@sylius.factory.oauth_user"
            - "@sylius.repository.oauth_user"
            - "@sylius.manager.shop_user"
            - "@sylius.canonicalizer"
            - "@app.repository.customer"

    App\Twig\ShopExtension:
        arguments:
            - '%app_locales%'

    App\Twig\CategoryExtension:
        arguments:
            - '@app.repository.category'
